name: iotdb-snap
version: "0.13.0-rev0"
summary: Apache IoTDB
description: |
  Apache IoTDB is cool
base: core20

confinement: strict
grade: stable

apps:
  server:
    command: apache-iotdb-0.13.0-all-bin/sbin/start-server.sh
    daemon: simple
    plugs: [network, network-bind, home, system-files]
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-amd64"
  cli:
    command: apache-iotdb-0.13.0-all-bin/sbin/start-cli.sh
    plugs: [network]
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-amd64"


parts:
  iotdb:
    build-packages:
      - wget
      - unzip
    stage-packages:
      - openjdk-11-jre-headless
      - ca-certificates
      - ca-certificates-java
    plugin: nil
    override-build: |
      # Download binary release
      wget -O $SNAPCRAFT_PART_INSTALL/iotdb.zip https://dlcdn.apache.org/iotdb/0.13.0/apache-iotdb-0.13.0-all-bin.zip
      unzip $SNAPCRAFT_PART_INSTALL/iotdb.zip -d $SNAPCRAFT_PART_INSTALL/
      # Copy over
      cp ../../../iotdb-engine.properties $SNAPCRAFT_PART_INSTALL/apache-iotdb-0.13.0-all-bin/conf/
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/cacerts
