name: apache-iotdb
version: 1.2.2
summary: Apache IoTDB
description: Apache IoTDB 1.2.2
base: core22
architectures:
  - build-on: [amd64, arm64]
    build-for: amd64
  - build-on: [arm64, amd64]
    build-for: arm64

grade: stable
confinement: strict

plugs:
  # See https://snapcraft.io/docs/system-files-interface
  sysctl-config:
    interface: system-files
    read:
    - /etc/sysctl.conf

apps:
  server:
    command: apache-iotdb-1.2.2-all-bin/sbin/start-standalone.sh
    daemon: simple
    plugs: [network, network-bind, home, sysctl-config]
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-$CRAFT_TARGET_ARCH"
  cli:
    command: apache-iotdb-1.2.2-all-bin/sbin/start-cli.sh
    plugs: [network]
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-$CRAFT_TARGET_ARCH"

parts:
  # Install all prerequisites for IoTDB (Mainly Java) and download and unpack IoTDB distribution
  iotdb:
    plugin: nil
    build-packages:
      - wget
      - unzip
    stage-packages:
      - openjdk-11-jre-headless
      - ca-certificates
      - ca-certificates-java
    override-build: |
      # Download and unpack binary release
      wget -O $SNAPCRAFT_PART_INSTALL/iotdb.zip https://dlcdn.apache.org/iotdb/1.2.2/apache-iotdb-1.2.2-all-bin.zip
      unzip $SNAPCRAFT_PART_INSTALL/iotdb.zip -d $SNAPCRAFT_PART_INSTALL/
      # Delete the existing properties, as we'll be overlaying them with our own. 
      rm $SNAPCRAFT_PART_INSTALL/apache-iotdb-1.2.2-all-bin/conf/*.properties
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/cacerts

  # Overlay the configuration files
  configs:
    plugin: dump
    source: config
    organize:
      '*': apache-iotdb-1.2.2-all-bin/conf/
